name: fix-code-style

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - weblate

    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  call-php-code-styling-workflow:
    uses: teamnovu/.github/.github/workflows/php-cs-fixer.yml@main
